// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlUfCkDWaPqCsTCraI7yEvTdOwZAUPbjM',
    appId: '1:536033983767:web:63086caaa9e8685b9d8b52',
    messagingSenderId: '536033983767',
    projectId: 'login-963cd',
    authDomain: 'login-963cd.firebaseapp.com',
    storageBucket: 'login-963cd.firebasestorage.app',
    measurementId: 'G-V8HLRTBEGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-i7ShwhnV6tQZVzt91xPNqPiEQQsTkgY',
    appId: '1:536033983767:android:9511f446a456e8949d8b52',
    messagingSenderId: '536033983767',
    projectId: 'login-963cd',
    storageBucket: 'login-963cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARs4t9DU3IAMl3FNnsSGG6OpwgB3OgyXo',
    appId: '1:536033983767:ios:e22de385d49a09a09d8b52',
    messagingSenderId: '536033983767',
    projectId: 'login-963cd',
    storageBucket: 'login-963cd.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARs4t9DU3IAMl3FNnsSGG6OpwgB3OgyXo',
    appId: '1:536033983767:ios:e22de385d49a09a09d8b52',
    messagingSenderId: '536033983767',
    projectId: 'login-963cd',
    storageBucket: 'login-963cd.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlUfCkDWaPqCsTCraI7yEvTdOwZAUPbjM',
    appId: '1:536033983767:web:5568a34c1dcd6bb79d8b52',
    messagingSenderId: '536033983767',
    projectId: 'login-963cd',
    authDomain: 'login-963cd.firebaseapp.com',
    storageBucket: 'login-963cd.firebasestorage.app',
    measurementId: 'G-JVB3VN1DLZ',
  );
}
