// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhNrw2TlFr4wQkMeGMHD8dNtnLnAfYDSw',
    appId: '1:524539152215:web:549c53e28dd420ad20a012',
    messagingSenderId: '524539152215',
    projectId: 'appi-bb7c9',
    authDomain: 'appi-bb7c9.firebaseapp.com',
    storageBucket: 'appi-bb7c9.firebasestorage.app',
    measurementId: 'G-FRCKB2K8K2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-TFfIvRcQlEn_g1C9ltVy4frbIOAzxWY',
    appId: '1:524539152215:android:8431895b3e2a711420a012',
    messagingSenderId: '524539152215',
    projectId: 'appi-bb7c9',
    storageBucket: 'appi-bb7c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBFBBsu_VW1uoxua60R5SU_SCYFPMP24w',
    appId: '1:524539152215:ios:f647321441f08c1920a012',
    messagingSenderId: '524539152215',
    projectId: 'appi-bb7c9',
    storageBucket: 'appi-bb7c9.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBFBBsu_VW1uoxua60R5SU_SCYFPMP24w',
    appId: '1:524539152215:ios:f647321441f08c1920a012',
    messagingSenderId: '524539152215',
    projectId: 'appi-bb7c9',
    storageBucket: 'appi-bb7c9.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhNrw2TlFr4wQkMeGMHD8dNtnLnAfYDSw',
    appId: '1:524539152215:web:45b3998d06869c1020a012',
    messagingSenderId: '524539152215',
    projectId: 'appi-bb7c9',
    authDomain: 'appi-bb7c9.firebaseapp.com',
    storageBucket: 'appi-bb7c9.firebasestorage.app',
    measurementId: 'G-XPHN1ZEL9Y',
  );
}
